'use strict';
(() => {
if (!window.THREE) { document.querySelector('#loading').innerHTML='연결을 확인해주세요<small>Three.js CDN을 불러오지 못했습니다. 인터넷 연결 후 새로고침해주세요.</small>'; return; }
const CONFIG = window.CONFIG = {
 race:{laps:3,aiCount:5}, vehicle:{acceleration:19,maxSpeed:32,braking:33,grip:9,lateralGrip:9,drag:.32,steering:1.65},
 drift:{grip:1.65,chargeRate:1,level1:.6,level2:1.35,level3:2.3}, boost:{duration:1.8,speedMultiplier:1.45},
 item:{respawnTime:4000,shieldDuration:3000,missileSpeed:53,weightsFront:[1,1,2,4,4],weightsBack:[4,4,1,2,3]},
 leaderboard:{maxEntries:10,keepBestOnly:false}, track:{width:15,samples:720}, particles:150
};
const CHARACTERS=[
 {id:'pikachu',name:'피카츄',color:0xf5ce32,icon:'ϟ',desc:'전기를 품은 노란 레이서',type:'mouse'},
 {id:'eevee',name:'이브이',color:0xb87942,icon:'🦊',desc:'폭신한 목털과 커다란 귀',type:'fox'},
 {id:'charmander',name:'파이리',color:0xf48a36,icon:'🔥',desc:'불꽃 꼬리의 열정 레이서',type:'fire'},
 {id:'bulbasaur',name:'이상해씨',color:0x60cbb0,icon:'🌱',desc:'등에 씨앗을 품은 친구',type:'plant'},
 {id:'pidgeotto',name:'피죤',color:0xcba363,icon:'🪶',desc:'붉은 볏과 힘찬 날개',type:'bird'},
 {id:'snorlax',name:'잠만보',color:0x397d87,icon:'💤',desc:'느긋한 표정, 묵직한 존재감',type:'sleep'}
];
const ITEM_NAMES=['유도 로켓','물폭탄','미끄럼 트랩','실드','순간 부스터'], ITEM_ICONS=['🚀','💧','🌀','◈','ϟ'];
const $=s=>document.querySelector(s), ui=$('#ui'), keys=new Set(),virtualKeys=new Set();
const pressed=code=>keys.has(code)||virtualKeys.has(code);
document.body.classList.toggle('touch-enabled',matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0);
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)), wrap=x=>(x%1+1)%1, angle=x=>Math.atan2(Math.sin(x),Math.cos(x));
const formatTime=window.formatTime=ms=>{if(!Number.isFinite(ms))return '--:--.---';ms=Math.max(0,Math.floor(ms));return `${String(Math.floor(ms/60000)).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}.${String(ms%1000).padStart(3,'0')}`;};
let state='MENU',profile={name:'',characterId:'pikachu'},selected=0,mode='speed',racers=[],player=null,elapsed=0,countdown=0,phaseTime=0,pausedFrom='',last=performance.now(),debug=false,fps=60,record=null,registered=false,fromRace=false;
let duel=null;
let boxes=[],effects=[],particles=[],skids=[],toastTime=0,preview=null,audio=null,engine=null,engineGain=null,muted=false;
const renderer=new THREE.WebGLRenderer({canvas:$('#world'),antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
const scene=new THREE.Scene();scene.background=new THREE.Color(0xa6dacf);scene.fog=new THREE.Fog(0xa6dacf,110,340);
const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,650);
scene.add(new THREE.HemisphereLight(0xd8f7ff,0x4c7144,2.4));const sun=new THREE.DirectionalLight(0xffedc1,3);sun.position.set(80,130,-50);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-160,right:160,top:160,bottom:-160,near:1,far:350});sun.shadow.bias=-.0008;scene.add(sun);
const mats=new Map(), geos=new Map();
function mat(color,extra={}){const key=color+JSON.stringify(extra);if(!mats.has(key))mats.set(key,new THREE.MeshStandardMaterial({color,roughness:.75,...extra}));return mats.get(key);}
function mesh(parent,type,color,pos=[0,0,0],scale=[1,1,1],extra={}){let geo=geos.get(type);if(!geo){geo=type==='sphere'?new THREE.SphereGeometry(1,16,12):type==='cone'?new THREE.ConeGeometry(1,2,8):type==='cylinder'?new THREE.CylinderGeometry(1,1,1,12):type==='torus'?new THREE.TorusGeometry(1,.14,8,20):new THREE.BoxGeometry(1,1,1);geos.set(type,geo);}const m=new THREE.Mesh(geo,mat(color,extra));m.position.set(...pos);m.scale.set(...scale);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function character(index){const c=CHARACTERS[index],g=new THREE.Group(),cream=0xffe4a4;const sleep=c.type==='sleep';
 mesh(g,'sphere',c.color,[0,.6,0],[sleep?.71:.46,sleep?.76:.57,.39]);mesh(g,'sphere',sleep?0xf3e1b7:cream,[0,.57,.3],[sleep?.54:.32,.42,.12]);
 mesh(g,'sphere',c.color,[0,1.22,.04],[sleep?.62:.55,.5,.44]);
 for(const s of [-1,1]){mesh(g,'sphere',c.color,[s*.48,.62,.16],[.19,.29,.2]).rotation.z=s*.6;mesh(g,'sphere',cream,[s*.26,.12,.27],[.23,.16,.3]);}
 if(c.type==='mouse'||c.type==='fox'){for(const s of [-1,1]){const ear=mesh(g,'sphere',c.color,[s*.38,1.94,0],[.16,.63,.12]);ear.rotation.z=-s*.35;const tip=mesh(g,'sphere',c.type==='mouse'?0x28252b:0x50312e,[s*.52,2.25,.07],[.11,.29,.075]);tip.rotation.z=-s*.35;}if(c.type==='mouse'){for(const s of [-1,1])mesh(g,'sphere',0xed5345,[s*.4,1.08,.365],[.14,.13,.06]);const tail=new THREE.Group();tail.position.set(.25,.65,-.4);tail.rotation.z=-.3;mesh(tail,'box',c.color,[.22,.1,-.12],[.17,.65,.14]).rotation.z=-.8;mesh(tail,'box',c.color,[.38,.48,-.12],[.48,.25,.14]);mesh(tail,'box',c.color,[.65,.78,-.12],[.3,.65,.14]).rotation.z=-.5;g.add(tail);}else{for(let k=0;k<9;k++){let a=k*Math.PI*2/9;mesh(g,'sphere',cream,[Math.sin(a)*.42,.87,Math.cos(a)*.3],[.22,.25,.23]);}mesh(g,'sphere',c.color,[.35,.56,-.66],[.35,.35,.62]).rotation.x=.6;mesh(g,'cone',cream,[.35,.81,-1.04],[.27,.3,.3]).rotation.x=-.7;}}
 if(c.type==='fire'){mesh(g,'sphere',c.color,[0,.45,-.65],[.24,.23,.65]).rotation.x=-.35;mesh(g,'cone',0xff6631,[0,.88,-1.06],[.22,.42,.18],{emissive:0xf95208,emissiveIntensity:1});mesh(g,'cone',0xffdc44,[0,.85,-1.08],[.12,.29,.12],{emissive:0xffb300,emissiveIntensity:1});}
 if(c.type==='plant'){for(const s of [-1,1])mesh(g,'cone',c.color,[s*.38,1.65,.02],[.2,.26,.18]);mesh(g,'sphere',0x41833c,[0,1,-.57],[.54,.64,.5]);for(let k=0;k<5;k++){let a=k*1.26;mesh(g,'cone',0x73ad42,[Math.sin(a)*.19,1.53,-.57+Math.cos(a)*.16],[.23,.35,.22]).rotation.z=Math.sin(a)*-.4;}for(const s of [-1,1]){mesh(g,'box',0x268c78,[s*.33,1.4,.41],[.14,.12,.025]).rotation.z=s*.3;}}
 if(c.type==='bird'){for(const s of [-1,1]){for(let k=0;k<4;k++){const wing=mesh(g,'sphere',cream,[s*(.56+k*.14),.95+k*.08,-.05-k*.06],[.17,.12,.5-k*.055]);wing.rotation.z=-s*.5;}}mesh(g,'cone',0xe7ac57,[0,1.13,.6],[.18,.24,.16]).rotation.x=Math.PI/2;for(let k=0;k<4;k++)mesh(g,'sphere',0xc8514c,[(k-1.5)*.12,1.7,-k*.09],[.13,.26,.35]).rotation.x=-.6;}
 if(sleep){for(const s of [-1,1])mesh(g,'cone',c.color,[s*.42,1.7,0],[.18,.24,.18]);mesh(g,'sphere',0xf3e1b7,[0,1.19,.32],[.5,.32,.15]);}
 for(const s of [-1,1]){if(sleep){const eye=mesh(g,'box',0x23343c,[s*.21,1.28,.469],[.17,.028,.025]);eye.rotation.z=s*.15;}else{mesh(g,'sphere',0x201f2d,[s*.23,1.29,.43],[.082,.115,.05]);mesh(g,'sphere',0xffffff,[s*.23-.02,1.33,.474],[.027,.04,.017]);}}
 mesh(g,'sphere',0x472f30,[0,1.08,.485],[.12,.048,.025]);if(c.type==='fox')mesh(g,'sphere',0x35242a,[0,1.2,.48],[.065,.045,.035]);return g;
}
function kart(index){const g=new THREE.Group(),c=CHARACTERS[index];mesh(g,'box',0x202e36,[0,.45,0],[1.9,.35,2.6]);mesh(g,'box',c.color,[0,.72,.65],[1.65,.55,1.25]);mesh(g,'box',c.color,[0,.68,-.8],[1.9,.28,.42]);mesh(g,'box',0xeff4e8,[0,.55,1.32],[1.7,.16,.16]);mesh(g,'box',0x263c43,[0,.86,-.4],[.8,.7,.3]);
 for(const s of [-1,1]){mesh(g,'box',0xf1ffda,[s*.56,.84,1.29],[.35,.14,.04],{emissive:0xcaffd7,emissiveIntensity:.6});mesh(g,'box',c.color,[s*.89,.7,-.3],[.22,.35,1.8]);for(const z of [-.85,.85]){const wheel=mesh(g,'cylinder',0x263139,[s*1.01,.41,z],[.39,.28,.39]);wheel.rotation.z=Math.PI/2;const hub=mesh(g,'cylinder',0xd8ded6,[s*1.16,.41,z],[.21,.03,.21]);hub.rotation.z=Math.PI/2;}}
 const wheel=mesh(g,'torus',0x23333b,[0,1.12,.53],[.3,.3,.3]);wheel.rotation.x=-.5;const driver=character(index);driver.position.y=.7;driver.scale.setScalar(.78);g.add(driver);g.userData.driver=driver;const shield=mesh(g,'sphere',0x7cecff,[0,1,0],[1.55,1.65,1.8],{transparent:true,opacity:.23,emissive:0x209fcb,emissiveIntensity:.6,wireframe:true});shield.visible=false;g.userData.shield=shield;return g;}
const points=[[0,0],[0,75],[-35,110],[-88,98],[-108,53],[-78,12],[-116,-24],[-145,-62],[-116,-94],[-70,-80],[-48,-115],[0,-128],[62,-116],[90,-82],[55,-53],[86,-20],[55,10],[24,-20],[16,-50],[0,-44]].map(([x,z])=>new THREE.Vector3(x,0,z));
const curve=new THREE.CatmullRomCurve3(points,true,'centripetal'),N=CONFIG.track.samples,track=[],length=curve.getLength();
for(let i=0;i<N;i++){const p=curve.getPointAt(i/N),t=curve.getTangentAt(i/N).normalize();track.push({p,t,n:new THREE.Vector3(t.z,0,-t.x)});}
function sample(u,offset=0){const f=wrap(u)*N,i=Math.floor(f),a=track[i],b=track[(i+1)%N],r=f-i;return {x:THREE.MathUtils.lerp(a.p.x,b.p.x,r)+a.n.x*offset,z:THREE.MathUtils.lerp(a.p.z,b.p.z,r)+a.n.z*offset,yaw:Math.atan2(a.t.x,a.t.z),t:a.t,n:a.n};}
function nearest(x,z,hint){let best=Infinity,idx=0;const span=hint===undefined?N:45,start=hint===undefined?0:hint-span;for(let k=0;k<(hint===undefined?N:span*2+1);k++){const i=(start+k+N)%N,p=track[i].p,d=(p.x-x)**2+(p.z-z)**2;if(d<best){best=d;idx=i;}}const a=track[idx];return {i:idx,u:idx/N,d:Math.sqrt(best),offset:(x-a.p.x)*a.n.x+(z-a.p.z)*a.n.z};}
function ribbon(width,color,y){const pos=[],indices=[];for(let i=0;i<=N;i++){const a=track[i%N];for(const s of [-1,1])pos.push(a.p.x+a.n.x*width*s,y,a.p.z+a.n.z*width*s);if(i<N){let k=i*2;indices.push(k,k+2,k+1,k+1,k+2,k+3);}}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geo.setIndex(indices);geo.computeVertexNormals();const m=new THREE.Mesh(geo,mat(color));m.receiveShadow=true;scene.add(m);}
mesh(scene,'box',0x6b9c59,[-20,-1.1,-10],[650,2,600]);ribbon(10.1,0xc9b994,.02);ribbon(8.3,0xf0ecd4,.045);ribbon(7.5,0x546466,.07);
for(let i=0;i<N;i+=5){const a=track[i];for(const s of [-1,1]){const curb=mesh(scene,'box',i%10?0xf0e7ce:0xef7858,[a.p.x+a.n.x*7.8*s,.14,a.p.z+a.n.z*7.8*s],[.6,.15,length/N*5]);curb.rotation.y=Math.atan2(a.t.x,a.t.z);}
 if(i%15===0){const dash=mesh(scene,'box',0xd5d9be,[a.p.x,.085,a.p.z],[.12,.012,1.9]);dash.rotation.y=Math.atan2(a.t.x,a.t.z);}}
let seed=328;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
for(let i=0;i<260;i++){const x=rand()*390-215,z=rand()*330-175;if(nearest(x,z).d<13)continue;const h=3+rand()*7;mesh(scene,'cylinder',0x776143,[x,h*.2,z],[.35,h*.5,.35]);for(let k=0;k<3;k++)mesh(scene,'cone',[0x2e6a4c,0x3c8054,0x529453][i%3],[x,h*.5+k*h*.18,z],[h*.34-k*.25,h*.37,h*.34-k*.25]);}
for(let i=0;i<45;i++){const x=rand()*370-205,z=rand()*300-150;if(nearest(x,z).d<12)continue;const rock=mesh(scene,'sphere',0x8c9c8b,[x,.5,z],[1+rand()*2,1+rand()*1.5,1+rand()]);rock.rotation.y=rand()*5;}
for(let i=0;i<N;i+=12){if(i>N*.5&&i<N*.57)continue;const a=track[i];for(const s of [-1,1]){mesh(scene,'box',0xa3885b,[a.p.x+a.n.x*10.3*s,.85,a.p.z+a.n.z*10.3*s],[.22,1.7,.22]);const rail=mesh(scene,'box',0xc6b286,[a.p.x+a.n.x*10.3*s,1.15,a.p.z+a.n.z*10.3*s],[.2,.2,length/N*12+.5]);rail.rotation.y=Math.atan2(a.t.x,a.t.z);}}
function sign(text,w=9,h=2){const c=document.createElement('canvas');c.width=1024;c.height=256;const ctx=c.getContext('2d');ctx.fillStyle='#163b35';ctx.fillRect(0,0,1024,256);ctx.fillStyle='#d7ff44';ctx.font='900 94px sans-serif';ctx.textAlign='center';ctx.fillText(text,512,159);const m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(c),side:THREE.DoubleSide}));return m;}
const gantry=new THREE.Group();for(const s of [-1,1])mesh(gantry,'box',0x173e37,[s*8,3,0],[.7,6,.7]);mesh(gantry,'box',0x173e37,[0,6,0],[17,2,.8]);let banner=sign('KART RUSH',14,2);banner.position.set(0,6,-.45);banner.rotation.y=Math.PI;gantry.add(banner);scene.add(gantry);
for(let x=-7;x<7;x++)for(let z=0;z<2;z++)mesh(scene,'box',(x+z)%2?0xe8eddd:0x213a39,[x+.5,.1,z-.5],[1,.03,1]);
// A timber bridge and an open-ended tunnel keep the same driveable surface.
for(let j=0;j<24;j++){const a=sample(.405+j*.00095);const plank=mesh(scene,'box',j%2?0xb99b71:0xc7ab80,[a.x,.09,a.z],[15,.035,.95]);plank.rotation.y=a.yaw;for(const s of [-1,1]){const p=sample(.405+j*.00095,s*7.9);mesh(scene,'box',0x775e45,[p.x,1,p.z],[.2,2,.2]);}}
const water=mesh(scene,'box',0x55bbbc,[-139,-.35,-41],[42,.2,25],{metalness:.25,roughness:.3});
for(let j=0;j<19;j++){let a=sample(.695+j*.002);const g=new THREE.Group();g.position.set(a.x,0,a.z);g.rotation.y=a.yaw;for(const s of [-1,1])mesh(g,'box',0x667765,[s*8,3,0],[1,6,2.4]);mesh(g,'box',0x687d65,[0,6.2,0],[17,1,2.4]);if(j%4===0)mesh(g,'box',0xd8ffb0,[0,5.6,0],[2,.1,.35],{emissive:0xc4ff86,emissiveIntensity:2});scene.add(g);}
for(const [u,txt]of [[.17,'FOREST PARK'],[.34,'S CURVE'],[.52,'HAIRPIN'],[.68,'TUNNEL']]){let a=sample(u,-11);let s=sign(txt,6,1.5);s.position.set(a.x,3,a.z);s.rotation.y=a.yaw+Math.PI;scene.add(s);}
// Scenic distant hills.
for(let i=0;i<16;i++)mesh(scene,'cone',i%2?0x79a789:0x88b298,[-250+i*35,18,-205-rand()*25],[30+rand()*20,30+rand()*20,28]);
for(let i=0;i<28;i++){const x=rand()*400-200,z=rand()*350-175;if(nearest(x,z).d<15)continue;mesh(scene,'cylinder',0x786343,[x,2,z],[.55,4,.55]);for(let j=0;j<3;j++)mesh(scene,'sphere',[0x79ab56,0x5f9a50,0x8db863][j],[x+(j-1)*1.6,4.8+rand()*1.8,z],[2.6,2.5,2.5]);}
for(let i=0;i<16;i++){const x=rand()*500-250,z=rand()*450-220;for(let k=0;k<3;k++)mesh(scene,'sphere',0xeaf6e8,[x+k*5,60+Math.sin(i)*10,z],[8,3.5+k,4]);}
// Instance repeated scenery once: trees, curbs and fencing remain a small number of draw calls.
function instanceScenery(){scene.updateMatrixWorld(true);const groups=new Map();scene.traverse(o=>{if(!o.isMesh||o.material.map)return;const key=o.geometry.uuid+o.material.uuid;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(o);});for(const objects of groups.values()){if(objects.length<3)continue;const inst=new THREE.InstancedMesh(objects[0].geometry,objects[0].material,objects.length);objects.forEach((o,i)=>{inst.setMatrixAt(i,o.matrixWorld);o.parent.remove(o);});inst.castShadow=true;inst.receiveShadow=true;scene.add(inst);}}
instanceScenery();
const raceGroup=new THREE.Group();scene.add(raceGroup);const previewGroup=new THREE.Group();previewGroup.position.set(240,0,170);scene.add(previewGroup);mesh(previewGroup,'cylinder',0x244d43,[0,-.15,0],[3.3,.3,3.3]);
const portraits=[];
function buildPortraits(){const ps=new THREE.Scene(),pc=new THREE.PerspectiveCamera(36,1,.1,30);ps.background=new THREE.Color(0x25483f);ps.add(new THREE.HemisphereLight(0xffffff,0x71846a,3));const light=new THREE.DirectionalLight(0xfff4ce,3);light.position.set(3,5,5);ps.add(light);pc.position.set(2.6,2.3,4.8);pc.lookAt(0,1,0);const target=new THREE.WebGLRenderTarget(192,192);const pixels=new Uint8Array(192*192*4),canvas=document.createElement('canvas');canvas.width=192;canvas.height=192;const ctx=canvas.getContext('2d'),data=ctx.createImageData(192,192);for(let i=0;i<6;i++){const model=character(i);ps.add(model);renderer.setRenderTarget(target);renderer.render(ps,pc);renderer.readRenderTargetPixels(target,0,0,192,192,pixels);for(let y=0;y<192;y++)data.data.set(pixels.subarray((191-y)*192*4,(192-y)*192*4),y*192*4);ctx.putImageData(data,0,0);portraits.push(canvas.toDataURL());ps.remove(model);}renderer.setRenderTarget(null);target.dispose();}
buildPortraits();
function setPreview(){if(preview)previewGroup.remove(preview);preview=kart(selected);previewGroup.add(preview);}
function notify(s){$('#toast').textContent=s;$('#toast').classList.add('show');toastTime=3;}
function sound(freq=550,duration=.1){if(!audio||muted)return;const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.5,audio.currentTime+duration);g.gain.setValueAtTime(.06,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}
function startAudio(){try{if(!audio){audio=new(window.AudioContext||window.webkitAudioContext)();engine=audio.createOscillator();engine.type='sawtooth';engineGain=audio.createGain();engineGain.gain.value=0;engine.connect(engineGain).connect(audio.destination);engine.start();}audio.resume();}catch{}}
function shell(content,cls=''){ui.innerHTML=`<section class="screen ${cls}"><header class="topbar"><div class="brand">KART <b>RUSH</b></div><div class="tag">FOREST RACING PARK / 01</div></header>${content}</section>`;}
function button(id,fn){$('#'+id)?.addEventListener('click',fn);}
function changeState(s){state=s;if(s!=='RACING'){keys.clear();virtualKeys.clear();}phaseTime=0;$('#vignette').style.opacity=['RACING','COUNTDOWN','FINISHED'].includes(s)?'.2':'1';}
function menu(){leaveDuel();changeState('MENU');fromRace=false;setPreview();shell(`<div class="hero"><div class="eyebrow">CHASE THE PERFECT LAP</div><h1>KART<br><span>RUSH.</span></h1><p>숲을 가르는 짜릿한 드리프트.<br>여섯 명의 레이서, 단 하나의 가장 빠른 랩.</p><div class="actions"><button id="start" class="primary">게임 시작 &nbsp; ↗</button><button id="duel" class="secondary">1:1 로비</button><button id="hall" class="secondary">명예의 전당</button><button id="help" class="secondary">조작법</button></div></div><footer class="footer"><span>01 / FOREST CIRCUIT &nbsp; · &nbsp; 3 LAPS &nbsp; · &nbsp; 6 RACERS</span><span>BUILT FOR THE RUSH</span></footer>`);button('start',setup);button('duel',duelLobby);button('hall',()=>hall(false));button('help',help);}
function setup(){changeState('PLAYER_SETUP');shell(`<div class="panel center" style="max-width:510px"><div class="eyebrow">01 / MEET THE DRIVER</div><h2>YOUR RACE.<br>YOUR NAME.</h2><label for="name">PLAYER NAME</label><input id="name" maxlength="12" placeholder="이름을 입력하세요" autocomplete="off"><div class="error" id="nameError"></div><div class="actions"><button id="next" class="primary">캐릭터 선택 →</button><button id="back" class="secondary">뒤로</button></div></div>`);$('#name').value=profile.name;$('#name').focus();function next(){const name=$('#name').value.trim();if(!name){$('#nameError').textContent='플레이어 이름을 입력해주세요.';return;}if(!/^[가-힣ㄱ-ㅎㅏ-ㅣa-zA-Z0-9 ]{1,12}$/.test(name)){$('#nameError').textContent='한글, 영문, 숫자로 최대 12자 입력해주세요.';return;}profile.name=name;selectCharacter();}button('next',next);button('back',menu);$('#name').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.isComposing)next();});}
function selectCharacter(){changeState('CHARACTER_SELECT');setPreview();shell(`<div class="select-info"><div class="eyebrow">02 / CHOOSE YOUR RACER</div><label>PLAYER</label><h3 id="profileName"></h3><h2 id="charName"></h2><p class="description" id="charDesc"></p><p class="description">← → 선택 &nbsp; / &nbsp; ENTER 확정<br>모든 캐릭터는 같은 기본 성능으로 출발합니다.</p></div><div class="cards">${CHARACTERS.map((c,i)=>`<button class="card ${i===selected?'selected':''}" data-char="${i}"><img class="portrait" src="${portraits[i]}" alt="${c.name} 3D 미리보기"><b>${c.name}</b><small>${c.desc}</small></button>`).join('')}</div><div class="actions"><button id="choose" class="primary">선택 완료 →</button><button id="back" class="secondary">뒤로</button></div>`);$('#profileName').textContent=profile.name;updateSelection();ui.querySelectorAll('[data-char]').forEach(b=>b.onclick=()=>{selected=+b.dataset.char;updateSelection();});button('choose',()=>{profile.characterId=CHARACTERS[selected].id;selectMode();});button('back',setup);}
function updateSelection(){setPreview();$('#charName').textContent=CHARACTERS[selected].name;$('#charDesc').textContent=CHARACTERS[selected].desc;ui.querySelectorAll('[data-char]').forEach(b=>b.classList.toggle('selected',+b.dataset.char===selected));}
function selectMode(){changeState('MODE_SELECT');shell(`<div class="panel center"><div class="eyebrow">03 / SET THE PACE</div><h2>SELECT MODE</h2><div class="mode-grid"><button class="mode" data-mode="speed"><div class="symbol">ϟϟ</div><h3>스피드전</h3><p>코너를 길게 미끄러지고, 부스터를 모으세요.<br>드리프트와 완벽한 레이싱 라인의 승부.</p><label>DRIFT · CHARGE · BOOST</label></button><button class="mode" data-mode="item"><div class="symbol">◈</div><h3>아이템전</h3><p>빛나는 아이템 박스로 레이스를 뒤집으세요.<br>공격과 방어, 마지막 코너까지 예측 불가.</p><label>COLLECT · ATTACK · DEFEND</label></button></div><div class="actions"><button id="race" class="primary">레이스 시작 ↗</button><button id="back" class="secondary">캐릭터 선택</button></div></div>`);function update(){ui.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('selected',b.dataset.mode===mode));}ui.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;update();});update();button('race',startRace);button('back',selectCharacter);}
const DUEL_URL='/api/duel';
async function duelRequest(payload){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),7000);try{const response=await fetch(DUEL_URL+(payload.action==='status'?`?code=${encodeURIComponent(payload.code)}&token=${encodeURIComponent(payload.token)}`:''),payload.action==='status'?{signal:controller.signal,cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:controller.signal,cache:'no-store'});const data=await response.json();if(!response.ok){const error=new Error(data.error||'방에 연결할 수 없습니다.');error.status=response.status;throw error;}return data;}finally{clearTimeout(timer);}}
function leaveDuel(){if(!duel)return;const previous=duel;duel=null;if(state!=='DUEL_RESULT')duelRequest({action:'leave',code:previous.code,token:previous.token}).catch(()=>{});}
function duelLobby(){leaveDuel();changeState('DUEL_LOBBY');shell(`<div class="panel center duel-panel"><div class="eyebrow">PRIVATE RACE / TWO DRIVERS</div><h2>1:1 RACE LOBBY</h2><p class="description">두 기기에서 같은 사이트에 접속하세요. 방 코드를 공유하면 3랩 스피드전이 함께 시작됩니다.<br>1:1 경기 결과는 명예의 전당에 등록되지 않습니다.</p><label for="duelName">PLAYER NAME</label><input id="duelName" maxlength="12" placeholder="이름을 입력하세요" autocomplete="off"><label>CHARACTER</label><div class="duel-characters">${CHARACTERS.map((c,i)=>`<button class="duel-character ${i===selected?'selected':''}" data-duel-char="${i}"><img src="${portraits[i]}" alt=""><span>${c.name}</span></button>`).join('')}</div><div class="duel-actions"><button id="createRoom" class="primary">방 만들기</button><span class="duel-or">또는</span><input id="joinCode" maxlength="6" placeholder="6자리 입장코드" autocomplete="off" autocapitalize="characters" spellcheck="false"><button id="joinRoom" class="secondary">다른 게임 입장하기</button></div><div class="error" id="duelError" role="alert"></div><button id="back" class="secondary">메인 메뉴</button></div>`);$('#duelName').value=profile.name;ui.querySelectorAll('[data-duel-char]').forEach(b=>b.onclick=()=>{selected=+b.dataset.duelChar;ui.querySelectorAll('[data-duel-char]').forEach(card=>card.classList.toggle('selected',card===b));});button('back',menu);button('createRoom',()=>enterDuel('create'));button('joinRoom',()=>enterDuel('join'));$('#joinCode').addEventListener('keydown',e=>{if(e.key==='Enter')enterDuel('join');});}
async function enterDuel(action){const error=$('#duelError'),name=$('#duelName').value.trim();if(!/^[가-힣ㄱ-ㅎㅏ-ㅣa-zA-Z0-9 ]{1,12}$/.test(name)){error.textContent='이름을 한글·영문·숫자로 최대 12자 입력해주세요.';return;}const code=$('#joinCode').value.trim().toUpperCase();if(action==='join'&&!/^[A-HJ-NP-Z2-9]{6}$/.test(code)){error.textContent='6자리 입장코드를 확인해주세요.';return;}profile.name=name;profile.characterId=CHARACTERS[selected].id;error.textContent='서버에 연결하는 중…';ui.querySelectorAll('#createRoom,#joinRoom').forEach(b=>b.disabled=true);const token=crypto.randomUUID();try{const sent=Date.now(),data=await duelRequest({action,code,token,player:{name,characterId:profile.characterId}}),received=Date.now();if(state!=='DUEL_LOBBY')return;duel={code:data.code,token,role:data.role,host:data.host,guest:data.guest,startAt:data.startAt,clockOffset:data.now-(sent+received)/2,seq:0,nextPoll:0,inFlight:false,peerSeenAt:0,winner:null,hostState:null,guestState:null};mode='speed';showDuelWaiting();applyDuelData(data);}catch(cause){if(state==='DUEL_LOBBY'){error.textContent=cause.message;ui.querySelectorAll('#createRoom,#joinRoom').forEach(b=>b.disabled=false);}}}
function showDuelWaiting(){changeState('DUEL_WAIT');shell(`<div class="panel center duel-wait"><div class="eyebrow">PRIVATE RACE / ROOM CODE</div><h2>READY TO RUSH?</h2><div class="duel-code" id="roomCode"></div><p class="description">다른 기기에서 <b>1:1 로비 → 다른 게임 입장하기</b>를 누르고 이 코드를 입력하세요.</p><div class="duel-players"><div><label>PLAYER 1</label><strong id="duelHost"></strong></div><div class="duel-versus">VS</div><div><label>PLAYER 2</label><strong id="duelGuest">상대 기다리는 중…</strong></div></div><p class="description" id="duelWaitStatus">상대가 입장하면 두 기기에서 카운트다운이 시작됩니다.</p><div class="actions"><button id="copyCode" class="primary">코드 복사</button><button id="leaveRoom" class="secondary">방 나가기</button></div></div>`);$('#roomCode').textContent=duel.code;$('#duelHost').textContent=duel.host.name;$('#duelGuest').textContent=duel.guest?.name||'상대 기다리는 중…';button('copyCode',async()=>{try{await navigator.clipboard.writeText(duel.code);notify('입장코드를 복사했습니다.');}catch{notify('화면의 코드를 직접 전달해주세요.');}});button('leaveRoom',()=>{leaveDuel();duelLobby();});}
function applyDuelData(data){if(!duel||data.code!==duel.code)return;duel.host=data.host;duel.guest=data.guest;duel.startAt=data.startAt;duel.hostState=data.hostState;duel.guestState=data.guestState;duel.winner=data.winner;const snapshot=duel.role==='host'?data.guestState:data.hostState,ownState=duel.role==='host'?data.hostState:data.guestState;if(state==='DUEL_WAIT'){if($('#duelGuest'))$('#duelGuest').textContent=data.guest?.name||'상대 기다리는 중…';if(snapshot?.abandoned){$('#duelWaitStatus').textContent='상대가 방을 나갔습니다. 새 방을 만들어주세요.';return;}if(data.guest&&data.startAt)startDuelRace();return;}const remote=racers[1];if(remote&&snapshot){remote.netTarget=snapshot;remote.speed=snapshot.speed;remote.lap=snapshot.lap;remote.checkpoint=snapshot.checkpoint;remote.raceProgress=snapshot.raceProgress;remote.finishTime=snapshot.finishTime;remote.lapTimes=snapshot.lapTimes;remote.bestLap=snapshot.lapTimes.length?Math.min(...snapshot.lapTimes):Infinity;remote.velocity.set(snapshot.vx,0,snapshot.vz);duel.peerSeenAt=data.now;}if($('#duelConnection'))$('#duelConnection').textContent=snapshot&&data.now-snapshot.updatedAt>3500?'상대 연결 끊김 · 복귀 대기':'상대 연결됨';if(state==='DUEL_RESULT')renderDuelResult();else if(ownState?.abandoned){notify('연결이 오래 끊겨 기권 처리되었습니다.');duelResults();}else if(snapshot?.abandoned){notify('상대가 방을 나갔습니다.');duelResults();}}
function startDuelRace(){if(!duel||state!=='DUEL_WAIT')return;startAudio();clearRace();mode='speed';elapsed=0;const peer=duel.role==='host'?duel.guest:duel.host;if(!peer)return;const otherIndex=CHARACTERS.findIndex(c=>c.id===peer.characterId);racers=[createRacer(selected,0),createRacer(otherIndex<0?0:otherIndex,1)];player=racers[0];racers[1].name=peer.name;racers[1].isRemote=true;const u=wrap(-.009);for(let i=0;i<2;i++){const offset=(i===0?(duel.role==='host'?-2.3:2.3):(duel.role==='host'?2.3:-2.3)),p=sample(u,offset),r=racers[i];r.x=p.x;r.z=p.z;r.yaw=p.yaw;r.u=u;r.prevU=u;r.near=Math.floor(u*N);}changeState('COUNTDOWN');hud();const exit=document.createElement('button');exit.id='duelQuit';exit.className='duel-exit secondary';exit.textContent='경기 나가기';exit.addEventListener('click',()=>{leaveDuel();menu();});$('.hud').append(exit);updateModels(0);camera.position.set(player.x-Math.sin(player.yaw)*8,5,player.z-Math.cos(player.yaw)*8);camera.lookAt(player.x,1,player.z);sound(700,.15);}
async function pollDuel(){if(!duel||duel.inFlight)return;const current=duel;current.inFlight=true;const racing=['RACING','FINISHED'].includes(state);const payload=racing&&player?{action:'update',code:current.code,token:current.token,seq:++current.seq,snapshot:{x:player.x,z:player.z,yaw:player.yaw,vx:player.velocity.x,vz:player.velocity.z,speed:player.speed,lap:player.lap,checkpoint:player.checkpoint,raceProgress:player.raceProgress,elapsed,finishTime:player.finishTime,lapTimes:player.lapTimes}}:{action:'status',code:current.code,token:current.token};const sent=Date.now();try{const data=await duelRequest(payload),received=Date.now();if(duel!==current)return;current.clockOffset=THREE.MathUtils.lerp(current.clockOffset,data.now-(sent+received)/2,.2);current.nextPoll=performance.now()+(state==='RACING'?320:650);applyDuelData(data);}catch(error){if(duel!==current)return;current.nextPoll=performance.now()+1200;if(error.status===404||error.status===410){notify(error.message);leaveDuel();duelLobby();return;}if(error.status===409){try{applyDuelData(await duelRequest({action:'status',code:current.code,token:current.token}));}catch{}return;}if($('#duelConnection'))$('#duelConnection').textContent='연결 재시도 중…';if(state==='DUEL_WAIT'&&$('#duelWaitStatus'))$('#duelWaitStatus').textContent='연결 재시도 중… '+error.message;}finally{current.inFlight=false;}}
function duelResults(){if(!duel||state==='DUEL_RESULT')return;changeState('DUEL_RESULT');shell(`<div class="panel center duel-result"><div class="eyebrow">PRIVATE RACE / NO HALL OF FAME ENTRY</div><h2 id="duelVerdict">결과 확인 중…</h2><p class="description">이 경기 기록은 명예의 전당에 등록되지 않습니다.</p><div class="duel-score"><div><label>YOU</label><strong id="duelMyName"></strong><span id="duelMyTime"></span></div><div class="duel-versus">VS</div><div><label>RIVAL</label><strong id="duelPeerName"></strong><span id="duelPeerTime"></span></div></div><p class="description" id="duelResultStatus"></p><div class="actions"><button id="duelAgain" class="primary">새 방 만들기</button><button id="duelMenu" class="secondary">메인 메뉴</button></div></div>`);button('duelAgain',duelLobby);button('duelMenu',menu);renderDuelResult();if(duel.winner)duel.nextPoll=Infinity;}
function renderDuelResult(){if(state!=='DUEL_RESULT'||!duel)return;const opponent=duel.role==='host'?duel.guest:duel.host,peerState=duel.role==='host'?duel.guestState:duel.hostState;$('#duelMyName').textContent=profile.name;$('#duelPeerName').textContent=opponent?.name||'상대';$('#duelMyTime').textContent=player?.finishTime!=null?formatTime(player.finishTime):'미완주';$('#duelPeerTime').textContent=peerState?.finishTime!=null?formatTime(peerState.finishTime):peerState?.abandoned?'기권':'주행 중';$('#duelVerdict').textContent=duel.winner===duel.role?'YOU WIN!':duel.winner?'RIVAL WINS':'결과 확인 중…';$('#duelResultStatus').textContent=duel.winner?'두 기기의 경주 결과가 동기화되었습니다.':'상대의 완주 결과를 기다리는 중입니다.';if(duel.winner)duel.nextPoll=Infinity;}
function help(){changeState('HELP');shell(`<div class="panel center"><div class="eyebrow">DRIVER'S HANDBOOK</div><h2>TAKE CONTROL</h2><div class="controls"><div><kbd>W / ↑</kbd>가속</div><div><kbd>S / ↓</kbd>브레이크 / 후진</div><div><kbd>A D / ← →</kbd>조향</div><div><kbd>SHIFT + 조향</kbd>드리프트</div><div><kbd>SPACE</kbd>부스터</div><div><kbd>E / CTRL</kbd>아이템 사용</div><div><kbd>R</kbd>체크포인트 복귀</div><div><kbd>ESC</kbd>일시정지</div><div><kbd>F2</kbd>디버그</div><div><kbd>M</kbd>음소거</div></div><p class="description">드리프트를 유지하면 3단계까지 충전됩니다. Shift를 놓으면 미니 터보!<br>스피드전에서는 드리프트로 부스터도 획득합니다. 트랙 밖에서는 속도가 줄어듭니다.<br>정방향 체크포인트를 모두 통과한 3랩 기록만 명예의 전당에 등록됩니다.<br>모바일: ◀ / ▶ 조향, GO 가속, BRAKE 제동. DRIFT와 조향을 함께 누르세요. BOOST / ITEM, Ⅱ 일시정지도 화면 버튼으로 조작합니다.</p><button id="back" class="primary">메인 메뉴</button></div>`);button('back',menu);}
function clearRace(){raceGroup.clear();boxes=[];effects=[];for(const p of particles)scene.remove(p.mesh);particles=[];for(const s of skids)scene.remove(s.mesh);skids=[];racers=[];registered=false;record=null;}
function createRacer(charIndex,i){const gridSlot=i===0?4:i<=4?i-1:5,u=wrap(-.012-Math.floor(gridSlot/2)*.004),pos=sample(u,(gridSlot%2?1:-1)*2.2),model=kart(charIndex);raceGroup.add(model);return {id:i,charIndex,name:i===0?profile.name:['NOVA','RAY','MINT','JET','COCO'][i-1],model,x:pos.x,z:pos.z,yaw:pos.yaw,velocity:new THREE.Vector3(),forwardVelocity:0,lateralVelocity:0,speed:0,acceleration:CONFIG.vehicle.acceleration*(.92+i*.015),maxSpeed:CONFIG.vehicle.maxSpeed*(.85+i*.018),corneringSkill:.84+i*.026,racingLineOffset:(i%2?1:-1)*(1+i*.22),grip:CONFIG.vehicle.grip,lateralGrip:CONFIG.vehicle.lateralGrip,drag:CONFIG.vehicle.drag,driftGrip:CONFIG.drift.grip,steering:0,isDrifting:false,driftDirection:0,driftTime:0,driftCharge:0,boostGauge:0,boostCount:0,boostTime:0,shield:0,stun:0,spin:0,slow:0,items:[],lap:0,checkpoint:0,started:false,prevU:u,u,near:Math.floor(u*N),raceProgress:u-1,lapStart:0,lapTimes:[],bestLap:Infinity,finishTime:null,lastSafe:u,aiUse:2+rand()*3,itemCooldown:0,stuck:0,rank:i+1};}
function startRace(){startAudio();clearRace();elapsed=0;countdown=3.6;const order=[selected,...CHARACTERS.map((_,i)=>i).filter(i=>i!==selected)];racers=order.map(createRacer);player=racers[0];if(mode==='item'){for(const u of [.09,.24,.38,.53,.66,.83,.94])for(const offset of [-4,0,4]){const a=sample(u,offset),g=new THREE.Group();g.position.set(a.x,1.4,a.z);mesh(g,'box',0x91eddf,[0,0,0],[1.25,1.25,1.25],{transparent:true,opacity:.65,emissive:0x38d5b5,emissiveIntensity:.7});const label=sign('?',.8,.6);label.position.z=.64;g.add(label);raceGroup.add(g);boxes.push({g,x:a.x,z:a.z,cooldown:0});}}changeState('COUNTDOWN');hud();updateModels(0);const p=player;camera.position.set(p.x-Math.sin(p.yaw)*8,5,p.z-Math.cos(p.yaw)*8);camera.lookAt(p.x,1,p.z);sound(700,.15);}
function hud(){ui.innerHTML=`<div class="hud"><div class="map hud-box"><canvas id="minimap" width="360" height="270"></canvas><small>FOREST RACING PARK</small></div><div class="position"><label>POSITION</label><strong id="rank">1</strong><span> / ${duel?2:6}</span></div><div class="timing hud-box"><label>LAP</label><div class="lap"><span id="lap">1</span> / 3</div><div class="timer-row">CURRENT LAP <b id="currentTime">00:00.000</b></div><div class="timer-row">BEST LAP <b id="bestTime">--:--.---</b></div><div class="timer-row">TOTAL <b id="totalTime">00:00.000</b></div></div><div class="speed"><strong id="speed">0</strong><small>KM/H</small></div><div class="bottom-hud hud-box"><small id="driftLabel">SHIFT · DRIFT</small><div class="meter"><i id="driftMeter"></i></div><small id="boostLabel">SPACE · BOOST 0 / 2</small><div class="items" id="items"></div></div><div class="you">YOU</div><div class="race-hint">WASD 주행 · SHIFT 드리프트<br>SPACE 부스터 · E 아이템 · ESC 일시정지</div><div class="countdown" id="countdown"></div>${duel?'<div class="duel-hud">1:1 스피드전 · <span id="duelConnection">상대 연결 중…</span><br>명예의 전당 기록 제외</div>':''}<div class="touch-controls" aria-label="터치 주행 조작"><button class="touch-button touch-pause" data-touch-action="pause" aria-label="일시정지">Ⅱ</button><div class="touch-steering"><button class="touch-button" data-touch-hold="KeyA" aria-label="왼쪽으로 조향">◀</button><button class="touch-button" data-touch-hold="KeyD" aria-label="오른쪽으로 조향">▶</button></div><button class="touch-button touch-drift" data-touch-hold="ShiftLeft" aria-label="드리프트">DRIFT</button><button class="touch-button touch-special" data-touch-action="special" aria-label="${mode==='speed'?'부스터 사용':'아이템 사용'}">${mode==='speed'?'BOOST':'ITEM'}</button><button class="touch-button touch-brake" data-touch-hold="KeyS" aria-label="브레이크 또는 후진">BRAKE</button><button class="touch-button touch-accelerate" data-touch-hold="KeyW" aria-label="가속">GO</button><button class="touch-button touch-reset" data-touch-action="reset" aria-label="체크포인트로 복귀">↶</button></div></div>`;attachTouchControls();}
function attachTouchControls(){const heldPointers=new Map();const release=e=>{const code=heldPointers.get(e.pointerId);if(!code)return;heldPointers.delete(e.pointerId);if(![...heldPointers.values()].includes(code))virtualKeys.delete(code);e.currentTarget.classList.remove('active');};ui.querySelectorAll('[data-touch-hold]').forEach(button=>{button.addEventListener('pointerdown',e=>{if(state!=='COUNTDOWN'&&state!=='RACING')return;e.preventDefault();button.setPointerCapture(e.pointerId);heldPointers.set(e.pointerId,button.dataset.touchHold);virtualKeys.add(button.dataset.touchHold);button.classList.add('active');});for(const type of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(type,release);});ui.querySelectorAll('[data-touch-action]').forEach(button=>button.addEventListener('pointerdown',e=>{e.preventDefault();if(button.dataset.touchAction==='pause'){pause();return;}if(state!=='RACING')return;if(button.dataset.touchAction==='reset')resetRacer(player);else if(mode==='speed'&&player.boostCount>0){player.boostCount--;boost(player);}else if(mode==='item')useItem(player);}));}
function resetRacer(r){const a=sample(r.lastSafe,r.id? r.racingLineOffset:0);r.x=a.x;r.z=a.z;r.yaw=a.yaw;r.velocity.set(0,0,0);r.near=Math.floor(wrap(r.lastSafe)*N);r.prevU=wrap(r.lastSafe);r.isDrifting=false;r.driftCharge=0;r.stuck=0;if(!r.id)notify('체크포인트로 복귀 · 타이머는 유지됩니다');}
function level(r){return r.driftCharge>=CONFIG.drift.level3?3:r.driftCharge>=CONFIG.drift.level2?2:r.driftCharge>=CONFIG.drift.level1?1:0;}
function boost(r,duration=CONFIG.boost.duration){r.boostTime=Math.max(r.boostTime,duration);if(!r.id)sound(900,.25);}
function endDrift(r){if(!r.isDrifting)return;const l=level(r);if(l)boost(r,[0,.38,.65,1][l]);r.isDrifting=false;r.driftCharge=0;r.driftTime=0;}
function drive(r,dt){let throttle=0,steer=0,drift=false;const v=CONFIG.vehicle;
 if(r.id){const look=sample(r.u+(.012+r.speed/length*.48),r.racingLineOffset+Math.sin(elapsed*.0004+r.id)*.6);const target=Math.atan2(look.x-r.x,look.z-r.z),err=angle(target-r.yaw);const bend=Math.abs(angle(sample(r.u+.028).yaw-sample(r.u+.006).yaw));const targetSpeed=r.maxSpeed*clamp(1-bend*(.62-r.corneringSkill*.16),.48,1);throttle=r.speed<targetSpeed?1:-.3;steer=clamp(err*2.7,-1,1);drift=bend>.3&&bend<1.2&&r.speed>15&&Math.abs(err)<.7&&Math.sin(elapsed*.001+r.id)>.1;for(const other of racers){if(other===r)continue;const dx=other.x-r.x,dz=other.z-r.z;const forward=dx*Math.sin(r.yaw)+dz*Math.cos(r.yaw);if(forward>0&&forward<6&&dx*dx+dz*dz<30)steer+=clamp((r.racingLineOffset-other.racingLineOffset)*.1,-.22,.22);}r.aiUse-=dt;if(r.aiUse<=0){if(r.items.length)useItem(r);if(r.boostCount&&bend<.2){r.boostCount--;boost(r);}r.aiUse=2+rand()*3;}}
 else{throttle=(pressed('KeyW')||pressed('ArrowUp')?1:0)-(pressed('KeyS')||pressed('ArrowDown')?1:0);steer=(pressed('KeyA')||pressed('ArrowLeft')?1:0)-(pressed('KeyD')||pressed('ArrowRight')?1:0);drift=(pressed('ShiftLeft')||pressed('ShiftRight'))&&Math.abs(steer)>0;}
 // Positive yaw turns toward world +X (screen-left when moving forward).
 if(r.stun>0){throttle=0;steer=0;drift=false;}if(r.finishTime!==null){throttle=0;steer=0;drift=false;}
 r.steering=steer;const fx=Math.sin(r.yaw),fz=Math.cos(r.yaw),rx=Math.cos(r.yaw),rz=-Math.sin(r.yaw);let forward=r.velocity.x*fx+r.velocity.z*fz,lateral=r.velocity.x*rx+r.velocity.z*rz;
 if(drift&&forward>10){if(!r.isDrifting){r.isDrifting=true;r.driftDirection=Math.sign(steer);r.driftTime=0;}r.driftTime+=dt;r.driftCharge+=dt*CONFIG.drift.chargeRate;if(mode==='speed'){r.boostGauge+=dt*.31;if(r.boostGauge>=1){r.boostCount=Math.min(2,r.boostCount+1);r.boostGauge-=1;if(!r.id)notify('BOOST READY · SPACE');}}}else endDrift(r);
 const boosted=r.boostTime>0,max=(r.id?r.maxSpeed:v.maxSpeed)*(boosted?CONFIG.boost.speedMultiplier:1)*(r.slow>0?.55:1);
 if(throttle<0&&forward>1)forward-=v.braking*Math.abs(throttle)*dt;else forward+=throttle*(r.id?r.acceleration:v.acceleration)*(boosted?1.5:1)*dt;
 forward*=Math.exp(-v.drag*dt);forward=clamp(forward,-7,max);r.lateralGrip=r.isDrifting?r.driftGrip:v.lateralGrip;lateral*=Math.exp(-r.lateralGrip*dt);
 if(r.isDrifting)lateral=THREE.MathUtils.lerp(lateral,-r.driftDirection*Math.abs(forward)*.25,1-Math.exp(-dt*3));
 r.velocity.x=fx*forward+rx*lateral;r.velocity.z=fz*forward+rz*lateral;
 const steerRate=v.steering*(1-Math.min(Math.abs(forward)/45,.35))*Math.min(Math.abs(forward)/7,1)*(r.isDrifting?1.15:1)*(r.slow>0?.55:1);r.yaw+=steer*steerRate*dt*(forward>=0?1:-1);if(r.spin>0)r.yaw+=dt*5;
 r.x+=r.velocity.x*dt;r.z+=r.velocity.z*dt;const near=nearest(r.x,r.z,r.near);r.near=near.i;r.u=near.u;r.surface=near.d>7.5?'GRASS':'ROAD';
 if(near.d>7.5)r.velocity.multiplyScalar(Math.exp(-dt*1.8));if(near.d>9.3){const a=track[near.i],side=Math.sign(near.offset);r.x=a.p.x+a.n.x*side*9.25;r.z=a.p.z+a.n.z*side*9.25;const vn=r.velocity.x*a.n.x+r.velocity.z*a.n.z;if(vn*side>0){r.velocity.x-=a.n.x*vn*1.35;r.velocity.z-=a.n.z*vn*1.35;}r.velocity.multiplyScalar(.92);}if(near.d>24)resetRacer(r);
 r.speed=r.velocity.length();r.forwardVelocity=r.velocity.x*Math.sin(r.yaw)+r.velocity.z*Math.cos(r.yaw);r.lateralVelocity=r.velocity.x*Math.cos(r.yaw)-r.velocity.z*Math.sin(r.yaw);
 if(r.id){r.stuck=r.speed<3?r.stuck+dt:0;if(r.stuck>2.5)resetRacer(r);}
 for(const key of ['boostTime','shield','stun','spin','slow','itemCooldown'])r[key]=Math.max(0,r[key]-dt);
 checkpoint(r);if(r.isDrifting&&Math.random()<dt*30){emit(r.x,r.z,level(r)>1?0xffc756:0x92e8f3,2);tireMark(r);}if(boosted&&Math.random()<dt*35)emit(r.x-Math.sin(r.yaw),r.z-Math.cos(r.yaw),0xc7ff40,2);
}
const CP=24;
function checkpoint(r){if(r.finishTime!==null)return;const du=r.u-r.prevU;const delta=du<-.5?du+1:du>.5?du-1:du;const forward=delta>0&&delta<.06;const crosses=t=>{let d=wrap(t-r.prevU);return forward&&d>0&&d<=delta+.00001;};
 if(!r.started){if(crosses(0)){r.started=true;r.lapStart=0;r.checkpoint=1;r.lastSafe=.003;}}
 else if(r.checkpoint<CP&&crosses(r.checkpoint/CP)){r.lastSafe=r.checkpoint/CP;r.checkpoint++;}
 else if(r.checkpoint===CP&&crosses(0)){const time=elapsed-r.lapStart;r.lapTimes.push(time);r.bestLap=Math.min(r.bestLap,time);r.lap++;r.lapStart=elapsed;r.checkpoint=1;r.lastSafe=.003;if(!r.id){sound(1100,.25);notify(r.lap<3?`LAP ${r.lap+1} · ${formatTime(time)}`:'FINISH!');}if(r.lap>=CONFIG.race.laps){r.finishTime=elapsed;if(!r.id)finishRace();}}
 r.prevU=r.u;const sector=r.started?r.checkpoint-1:-1;const sectorStart=r.started?sector/CP:0;let within=r.started?clamp((r.u-sectorStart)*CP,0,.999):r.u-1;r.raceProgress=r.lap+(r.started?(sector+within)/CP:within);
}
function rankRacers(){const order=[...racers].sort((a,b)=>a.finishTime!==null&&b.finishTime!==null?a.finishTime-b.finishTime:a.finishTime!==null?-1:b.finishTime!==null?1:b.raceProgress-a.raceProgress);order.forEach((r,i)=>r.rank=i+1);return order;}
function collision(){for(let i=0;i<racers.length;i++)for(let j=i+1;j<racers.length;j++){const a=racers[i],b=racers[j];if(a.finishTime!==null||b.finishTime!==null)continue;const dx=b.x-a.x,dz=b.z-a.z,d=Math.hypot(dx,dz);if(d>0&&d<1.8){const push=(1.8-d)*.5,nx=dx/d,nz=dz/d;a.x-=nx*push;a.z-=nz*push;b.x+=nx*push;b.z+=nz*push;}}}
function weightedItem(r){const weights=r.rank<=3?CONFIG.item.weightsFront:CONFIG.item.weightsBack;let n=Math.random()*weights.reduce((a,b)=>a+b,0);for(let i=0;i<5;i++){n-=weights[i];if(n<=0)return i;}return 4;}
function useItem(r){if(!r.items.length||r.stun>0)return;const type=r.items.shift();if(!r.id){notify(ITEM_NAMES[type]);sound(650,.2);}if(type===3){r.shield=CONFIG.item.shieldDuration/1000;return;}if(type===4){boost(r,2);return;}let x=r.x,z=r.z,g;
 if(type===0){const ahead=racers.filter(o=>o!==r&&o.finishTime===null&&(o.x-r.x)*Math.sin(r.yaw)+(o.z-r.z)*Math.cos(r.yaw)>0).sort((a,b)=>(a.x-r.x)**2+(a.z-r.z)**2-((b.x-r.x)**2+(b.z-r.z)**2));g=mesh(raceGroup,'cone',0xf27852,[x,1,z],[.3,.6,.3],{emissive:0xdb5024});effects.push({type,owner:r.id,target:ahead[0]||null,g,x,z,dx:Math.sin(r.yaw),dz:Math.cos(r.yaw),life:5});}
 if(type===1){g=mesh(raceGroup,'sphere',0x55c7ef,[x,1,z],[.55,.55,.55],{metalness:.4,roughness:.1});effects.push({type,owner:r.id,g,x,z,dx:Math.sin(r.yaw)*22,dz:Math.cos(r.yaw)*22,life:1.1,age:0});}
 if(type===2){x-=Math.sin(r.yaw)*3;z-=Math.cos(r.yaw)*3;g=mesh(raceGroup,'cylinder',0xd88afa,[x,.16,z],[1,.2,1],{emissive:0x602b8b});effects.push({type,owner:r.id,g,x,z,life:24});}}
function hit(r,type){if(r.shield>0){r.shield=0;emit(r.x,r.z,0x85faff,12);if(!r.id)notify('SHIELD BLOCK!');return;}r.velocity.multiplyScalar(type===0?.22:.4);r.stun=type===0?.65:.2;r.slow=type===1?1.8:.5;r.spin=type===2?.65:0;emit(r.x,r.z,type===1?0x80daff:0xffbf65,18);if(!r.id){notify('피격! 다시 가속하세요');sound(180,.3);}}
function updateItems(dt){for(const b of boxes){b.cooldown=Math.max(0,b.cooldown-dt);b.g.visible=b.cooldown===0;b.g.rotation.y+=dt;b.g.position.y=1.45+Math.sin(elapsed*.003+b.x)*.2;if(b.cooldown===0)for(const r of racers){if(r.items.length<2&&r.itemCooldown===0&&Math.hypot(r.x-b.x,r.z-b.z)<2){r.items.push(weightedItem(r));r.itemCooldown=.35;b.cooldown=CONFIG.item.respawnTime/1000;b.g.visible=false;if(!r.id)sound(1300,.1);break;}}}
 for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.life-=dt;if(e.type===0){if(e.target&&e.target.finishTime===null){const d=Math.hypot(e.target.x-e.x,e.target.z-e.z);e.dx=THREE.MathUtils.lerp(e.dx,(e.target.x-e.x)/(d||1),Math.min(1,dt*5));e.dz=THREE.MathUtils.lerp(e.dz,(e.target.z-e.z)/(d||1),Math.min(1,dt*5));}const norm=Math.hypot(e.dx,e.dz)||1;e.x+=e.dx/norm*CONFIG.item.missileSpeed*dt;e.z+=e.dz/norm*CONFIG.item.missileSpeed*dt;e.g.position.set(e.x,1,e.z);e.g.rotation.set(Math.PI/2,0,-Math.atan2(e.dx,e.dz));for(const r of racers)if(r.id!==e.owner&&Math.hypot(r.x-e.x,r.z-e.z)<1.7){hit(r,0);e.life=0;break;}}
 if(e.type===1){e.age+=dt;e.x+=e.dx*dt;e.z+=e.dz*dt;e.g.position.set(e.x,1+Math.sin(e.age/1.1*Math.PI)*6,e.z);if(e.life<=0){emit(e.x,e.z,0x62d8ff,25);for(const r of racers)if(Math.hypot(r.x-e.x,r.z-e.z)<7)hit(r,1);}}
 if(e.type===2)for(const r of racers)if(r.id!==e.owner&&Math.hypot(r.x-e.x,r.z-e.z)<1.6){hit(r,2);e.life=0;break;}
 if(e.life<=0){raceGroup.remove(e.g);effects.splice(i,1);}}
}
function emit(x,z,color,count){for(let i=0;i<count&&particles.length<CONFIG.particles;i++){const m=mesh(scene,'sphere',color,[x,.4,z],[.12,.12,.12]);m.castShadow=false;particles.push({mesh:m,vx:(Math.random()-.5)*5,vz:(Math.random()-.5)*5,vy:1+Math.random()*3,life:.35+Math.random()*.45});}}
function tireMark(r){if(skids.length>200){scene.remove(skids[0].mesh);skids.shift();}for(const s of [-1,1]){const m=mesh(scene,'box',0x344240,[r.x+Math.cos(r.yaw)*s*.8,.092,r.z-Math.sin(r.yaw)*s*.8],[.18,.009,.65]);m.rotation.y=r.yaw;m.castShadow=false;skids.push({mesh:m,life:8});}}
function updateParticles(dt){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.mesh.position.x+=p.vx*dt;p.mesh.position.z+=p.vz*dt;p.mesh.position.y+=p.vy*dt;p.vy-=dt*5;p.mesh.scale.multiplyScalar(Math.exp(-dt*1.6));if(p.life<=0){scene.remove(p.mesh);particles.splice(i,1);}}for(let i=skids.length-1;i>=0;i--){skids[i].life-=dt;if(skids[i].life<=0){scene.remove(skids[i].mesh);skids.splice(i,1);}}}
function updateModels(dt){for(const r of racers){if(r.isRemote&&r.netTarget){const p=r.netTarget,lead=clamp((Date.now()+(duel?.clockOffset||0)-p.updatedAt)/1000,0,.28),a=1-Math.exp(-dt*10);r.x=THREE.MathUtils.lerp(r.x,p.x+p.vx*lead,a);r.z=THREE.MathUtils.lerp(r.z,p.z+p.vz*lead,a);r.yaw+=angle(p.yaw-r.yaw)*a;}r.model.position.set(r.x,.03,r.z);r.model.rotation.y=r.yaw;r.model.rotation.z=THREE.MathUtils.lerp(r.model.rotation.z,-r.steering*r.speed*.0019*(r.isDrifting?2:1),1-Math.exp(-dt*10));r.model.userData.shield.visible=r.shield>0;r.model.userData.driver.rotation.z=Math.sin(elapsed*.006+r.id)*.015;}}
const camTarget=new THREE.Vector3(),lookTarget=new THREE.Vector3();
function updateCamera(dt){if(['RACING','COUNTDOWN','PAUSED','FINISHED'].includes(state)&&player){const r=player,b=r.boostTime>0?1:0,d=7.6+r.speed*.052+b*1.1;camTarget.set(r.x-Math.sin(r.yaw)*d,4.4+r.speed*.025,r.z-Math.cos(r.yaw)*d);camera.position.lerp(camTarget,1-Math.exp(-dt*5.8));lookTarget.set(r.x+Math.sin(r.yaw)*6,1.25,r.z+Math.cos(r.yaw)*6);camera.lookAt(lookTarget);camera.fov=THREE.MathUtils.lerp(camera.fov,58+r.speed*.22+b*5,1-Math.exp(-dt*4));$('#speedLines').style.opacity=state==='RACING'&&b?'.65':'0';}else if(['CHARACTER_SELECT','RECORD_CARD'].includes(state)){const p=previewGroup.position;camera.position.set(p.x+6.5,3.8,p.z+8.8);camera.lookAt(p.x-2,1.1,p.z);camera.fov=45;preview.rotation.y+=dt*.45;preview.position.y=state==='RECORD_CARD'?Math.sin(phaseTime*4)*.06:0;$('#speedLines').style.opacity=0;}else{const a=sample(.03);camera.position.set(a.x-18,10,a.z+20);camera.lookAt(a.x+4,1,a.z);camera.fov=57;$('#speedLines').style.opacity=0;}camera.updateProjectionMatrix();}
function updateHUD(){if(!$('#rank')||!player)return;$('#rank').textContent=player.rank;$('#lap').textContent=Math.min(3,player.lap+1);$('#speed').textContent=Math.round(player.speed*3.6);$('#currentTime').textContent=formatTime(player.finishTime!==null?player.lapTimes[2]:elapsed-player.lapStart);$('#bestTime').textContent=formatTime(player.bestLap);$('#totalTime').textContent=formatTime(player.finishTime??elapsed);$('#driftLabel').textContent=player.isDrifting?`DRIFT · LEVEL ${level(player)}  /  3`:'SHIFT · DRIFT';$('#driftMeter').style.width=`${clamp(player.driftCharge/CONFIG.drift.level3,0,1)*100}%`;$('#boostLabel').textContent=mode==='speed'?`SPACE · BOOST ${player.boostCount} / 2 · ${Math.round(player.boostGauge*100)}%`:'E / CTRL · USE ITEM';$('#items').textContent='';if(mode==='item')for(let i=0;i<2;i++){const el=document.createElement('span');el.className='item-slot';el.textContent=player.items[i]!==undefined?`${ITEM_ICONS[player.items[i]]} ${ITEM_NAMES[player.items[i]]}`:'◇ EMPTY';$('#items').append(el);}drawMap();}
function drawMap(){const c=$('#minimap');if(!c)return;const ctx=c.getContext('2d');ctx.clearRect(0,0,360,270);const px=x=>(x+158)*1.26+15,pz=z=>(z+140)*.95+10;ctx.lineJoin='round';ctx.lineCap='round';ctx.beginPath();track.forEach((a,i)=>i?ctx.lineTo(px(a.p.x),pz(a.p.z)):ctx.moveTo(px(a.p.x),pz(a.p.z)));ctx.closePath();ctx.strokeStyle='#a8bdaf55';ctx.lineWidth=14;ctx.stroke();ctx.strokeStyle='#d7e2c2';ctx.lineWidth=3;ctx.stroke();for(const r of [...racers].reverse()){ctx.fillStyle=r.id?'#'+CHARACTERS[r.charIndex].color.toString(16).padStart(6,'0'):'#d7ff44';ctx.beginPath();ctx.arc(px(r.x),pz(r.z),r.id?4:7,0,Math.PI*2);ctx.fill();if(!r.id){ctx.strokeStyle='white';ctx.lineWidth=2;ctx.stroke();}}}
function pause(){if(!['RACING','COUNTDOWN'].includes(state))return;if(duel){notify('1:1 경기에서는 일시정지할 수 없습니다.');return;}pausedFrom=state;changeState('PAUSED');shell(`<div class="panel center" style="max-width:440px;text-align:center"><div class="eyebrow">TAKE A BREATHER</div><h2>PAUSED</h2><p class="description">레이스 타이머가 멈췄습니다.</p><div class="actions"><button id="resume" class="primary">계속하기</button><button id="restart" class="secondary">다시 하기</button><button id="quit" class="secondary">메인 메뉴</button></div></div>`);button('resume',resume);button('restart',startRace);button('quit',menu);}
function resume(){changeState(pausedFrom);hud();}
function loadRecords(){try{const parsed=JSON.parse(localStorage.getItem('kartRushHallOfFame')||'[]');return(Array.isArray(parsed)?parsed:[]).filter(r=>r&&typeof r.playerName==='string'&&Number.isFinite(r.bestLapTime)&&r.bestLapTime>0&&Number.isFinite(r.totalTime)&&CHARACTERS.some(c=>c.id===r.characterId)&&['speed','item'].includes(r.mode)).sort((a,b)=>a.bestLapTime-b.bestLapTime).slice(0,CONFIG.leaderboard.maxEntries);}catch{return [];}}
function saveRecord(){if(registered||player.lapTimes.length!==3)return;registered=true;record={id:globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`,playerName:profile.name,characterId:CHARACTERS[selected].id,characterName:CHARACTERS[selected].name,bestLapTime:Math.min(...player.lapTimes),totalTime:player.finishTime,mode,date:new Date().toISOString(),lapTimes:[...player.lapTimes]};let rows=loadRecords();if(CONFIG.leaderboard.keepBestOnly){const old=rows.find(r=>r.playerName===record.playerName&&r.mode===mode);if(old&&old.bestLapTime<=record.bestLapTime){record.rank=null;return;}rows=rows.filter(r=>!(r.playerName===record.playerName&&r.mode===mode));}rows.push(record);rows.sort((a,b)=>a.bestLapTime-b.bestLapTime);record.rank=rows.findIndex(r=>r.id===record.id)+1;try{localStorage.setItem('kartRushHallOfFame',JSON.stringify(rows.slice(0,CONFIG.leaderboard.maxEntries)));}catch{notify('브라우저 저장 공간에 접근할 수 없어 기록을 영구 저장하지 못했습니다.');}}
function finishRace(){changeState('FINISHED');rankRacers();$('#countdown').textContent='FINISH!';fromRace=!duel;if(duel)duel.nextPoll=0;sound(1500,.5);}
function results(){if(duel){duelResults();return;}changeState('RESULT');const order=rankRacers();shell(`<div class="panel center"><div class="eyebrow">THE FINISH LINE IS JUST THE BEGINNING</div><h2>RACE RESULT</h2><table class="table"><thead><tr><th>POS</th><th>RACER</th><th>CHARACTER</th><th>TIME / STATUS</th></tr></thead><tbody id="resultRows"></tbody></table><div class="result-stats"><div><label>TOTAL TIME</label><b>${formatTime(player.finishTime)}</b></div><div><label>BEST LAP</label><b>${formatTime(player.bestLap)}</b></div>${player.lapTimes.map((t,i)=>`<div><label>LAP ${i+1}</label><b>${formatTime(t)}</b></div>`).join('')}</div><button id="record" class="primary">나의 기록 등록 →</button><p class="description" style="margin-bottom:0">미완주 AI는 플레이어 완주 시점의 진행 순서로 표시됩니다.</p></div>`);for(const r of order){const tr=document.createElement('tr');tr.dataset.racer=r.id;if(!r.id)tr.className='mine';for(const text of [r.rank,r.name,CHARACTERS[r.charIndex].name,r.finishTime!==null?formatTime(r.finishTime):`주행 중 · ${Math.min(3,r.lap+1)} LAP`]){const td=document.createElement('td');td.textContent=text;tr.append(td);}$('#resultRows').append(tr);}button('record',recordCard);}
const LEADERBOARD_URL='/api/leaderboard';
let hallRequest=0,onlineEntries=null,onlineError=false,onlineSaving=null;
async function leaderboardRequest(options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const response=await fetch(LEADERBOARD_URL,{...options,signal:controller.signal,cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'온라인 기록실 연결에 실패했습니다.');return data;}finally{clearTimeout(timer);}}
async function uploadRecord(){if(!record)return;const current=record;current.onlineStatus='saving';try{const data=await leaderboardRequest({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(current)});current.onlineStatus='saved';current.onlineRank=data.rank;if(state==='RECORD_CARD'&&record===current){$('#recordOnlineStatus').textContent=data.inTopTen?`온라인 명예의 전당 ${data.rank}위에 등록되었습니다.`:'온라인 기록실에 등록되었습니다. TOP 10 밖입니다.';if(data.rank===1){$('#recordHeadline').textContent='NEW HALL OF FAME RECORD!';$('#recordTitle').textContent='NEW RECORD';confetti();}}if(state==='HALL_OF_FAME')refreshHall();}catch(error){current.onlineStatus='failed';current.onlineError=error.message;if(state==='RECORD_CARD'&&record===current)$('#recordOnlineStatus').textContent='온라인 등록 실패 · 이 기기에 기록을 보관했습니다.';if(state==='HALL_OF_FAME')updateHallStatus();}}
function recordCard(){saveRecord();changeState('RECORD_CARD');setPreview();shell(`<div class="record-info"><div class="eyebrow" id="recordHeadline">YOUR RACE. YOUR RECORD.</div><h2 id="recordTitle">LAP COMPLETE</h2><div class="player-name" id="recordName"></div><p id="recordChar"></p><label>BEST LAP</label><div class="bigtime">${formatTime(player.bestLap)}</div><p class="eyebrow">${mode==='speed'?'SPEED MODE':'ITEM MODE'}</p><p class="description" id="recordOnlineStatus">온라인 명예의 전당에 등록하는 중…</p></div>`,'record-screen');$('#recordName').textContent=profile.name;$('#recordChar').textContent=CHARACTERS[selected].name;onlineSaving=uploadRecord();}
function confetti(){const root=document.createElement('div');root.className='celebrate';for(let i=0;i<50;i++){const e=document.createElement('i');e.className='confetti';e.style.left=Math.random()*100+'%';e.style.background=['#d7ff44','#77d9cd','#ffb877'][i%3];e.style.animationDelay=Math.random()*.8+'s';root.append(e);}ui.append(root);}
function renderHall(rows,recent){const body=$('#hallRows');if(!body)return;body.replaceChildren();for(let i=0;i<rows.length;i++){const r=rows[i],c=CHARACTERS.find(c=>c.id===r.characterId);if(!c)continue;const tr=document.createElement('tr');if(recent&&r.id===record?.id)tr.className='mine';for(const [j,value]of [String(i+1).padStart(2,'0'),c.name,r.playerName,formatTime(r.bestLapTime),r.mode==='speed'?'SPEED':'ITEM'].entries()){const td=document.createElement('td');td.textContent=value;if(j===1){td.textContent='';const portrait=document.createElement('img');portrait.src=portraits[CHARACTERS.indexOf(c)];portrait.alt=c.name;portrait.className='hall-portrait';td.append(portrait,document.createTextNode(c.name));}if(j===3)td.className='time';if(j===2&&recent&&r.id===record?.id){const badge=document.createElement('span');badge.className='badge';badge.textContent='★ YOUR RECORD';td.append(badge);}tr.append(td);}body.append(tr);}}
function updateHallStatus(){const status=$('#hallStatus');if(!status)return;const recent=!!$('#retry');if(onlineEntries){if(recent&&record?.onlineStatus==='failed'){status.textContent='온라인 등록에 실패했습니다. 이 기기에 기록을 보관했습니다. 아래에서 다시 시도할 수 있습니다.';return;}if(recent&&record?.onlineStatus==='saving'){status.textContent='온라인 기록 등록 중…';return;}if(recent&&record?.onlineStatus==='saved'&&(!record.onlineRank||record.onlineRank>10)){status.textContent=`YOUR BEST LAP ${formatTime(record.bestLapTime)} · OUTSIDE TOP 10`;return;}status.textContent=onlineEntries.length?'모든 플레이어가 공유하는 온라인 TOP 10입니다.':'아직 온라인 기록이 없습니다. 첫 번째 주인공이 되어보세요.';return;}status.textContent=onlineError?'온라인 기록실에 연결할 수 없어 이 기기에 저장된 기록을 표시합니다.':'온라인 기록을 불러오는 중…';}
async function refreshHall(){const request=++hallRequest;try{const data=await leaderboardRequest();if(request!==hallRequest||state!=='HALL_OF_FAME')return;onlineEntries=Array.isArray(data.entries)?data.entries:[];onlineError=false;renderHall(onlineEntries,!!$('#retry'));updateHallStatus();}catch{if(request!==hallRequest||state!=='HALL_OF_FAME')return;onlineEntries=null;onlineError=true;renderHall(loadRecords(),!!$('#retry'));updateHallStatus();}}
function hall(recent=false){changeState('HALL_OF_FAME');onlineEntries=null;onlineError=false;shell(`<div class="panel center" style="max-width:940px"><div class="eyebrow">FOREST PARK / ONLINE LAP RECORD ARCHIVE</div><h2>HALL OF <span style="color:var(--lime)">FAME.</span></h2><p class="description">모든 플레이어에게 공개되는 BEST LAP 기준 TOP 10.</p><table class="table"><thead><tr><th>#</th><th>CHARACTER</th><th>PLAYER</th><th>BEST LAP</th><th>MODE</th></tr></thead><tbody id="hallRows"></tbody></table><div id="hallStatus" class="description"></div><div class="actions" style="margin-top:22px">${recent?'<button id="retry" class="primary">다시 하기 ↗</button><button id="characters" class="secondary">캐릭터 선택</button>':''}<button id="back" class="secondary">${recent?'메인 메뉴':'뒤로'}</button><button id="sync" class="secondary" style="font-size:10px" hidden>온라인 등록 재시도</button><button id="clear" class="secondary" style="margin-left:auto;font-size:10px">이 기기 기록 삭제</button></div></div>`);renderHall(loadRecords(),recent);updateHallStatus();refreshHall();button('retry',startRace);button('characters',selectCharacter);button('back',menu);button('sync',async()=>{if(record&&record.onlineStatus==='failed'){onlineSaving=uploadRecord();await onlineSaving;}});button('clear',()=>{if(confirm('이 기기의 백업 기록만 삭제하시겠습니까? 온라인 기록은 유지됩니다.')){try{localStorage.removeItem('kartRushHallOfFame');if(!onlineEntries)renderHall([],recent);updateHallStatus();}catch{notify('기록을 삭제하지 못했습니다.');}}});if(recent){const sync=$('#sync');const showSync=()=>{if(sync)sync.hidden=record?.onlineStatus!=='failed';};showSync();onlineSaving?.finally(showSync);}}
window.addEventListener('keydown',e=>{if(e.code==='F2'){e.preventDefault();debug=!debug;$('#debug').hidden=!debug;return;}if(e.code==='KeyM'&&e.target.tagName!=='INPUT'){muted=!muted;notify(muted?'SOUND OFF':'SOUND ON');}if(e.target.tagName==='INPUT')return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','ControlLeft','ControlRight'].includes(e.code))e.preventDefault();if(state==='CHARACTER_SELECT'){if(e.code==='ArrowLeft'||e.code==='ArrowRight'){selected=(selected+(e.code==='ArrowLeft'?5:1))%6;updateSelection();}if(e.code==='Enter')$('#choose').click();return;}if(e.code==='Escape'){if(state==='PAUSED')resume();else pause();return;}if(state==='COUNTDOWN'){keys.add(e.code);return;}if(state!=='RACING')return;keys.add(e.code);if(e.repeat)return;if(e.code==='KeyR')resetRacer(player);if(e.code==='Space'&&mode==='speed'&&player.boostCount>0){player.boostCount--;boost(player);}if(['KeyE','ControlLeft','ControlRight'].includes(e.code)&&mode==='item')useItem(player);});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();virtualKeys.clear();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){virtualKeys.clear();pause();}});window.addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();});
function frame(now){requestAnimationFrame(frame);const raw=Math.max(0,(now-last)/1000),dt=Math.min(raw,.05);last=now;fps=THREE.MathUtils.lerp(fps,1/Math.max(.001,raw),.05);phaseTime+=dt;toastTime-=dt;if(toastTime<=0)$('#toast').classList.remove('show');
 if(state==='COUNTDOWN'){if(duel){const remaining=(duel.startAt-Date.now()-duel.clockOffset)/1000,shown=remaining>0?String(Math.ceil(remaining)):'GO!';if($('#countdown').textContent!==shown){$('#countdown').textContent=shown;sound(remaining>0?650:1200,.13);}if(remaining<=0){changeState('RACING');elapsed=Math.max(0,Date.now()+duel.clockOffset-duel.startAt);phaseTime=0;duel.nextPoll=0;}}else{const old=Math.ceil(countdown);countdown-=dt;$('#countdown').textContent=countdown>.6?Math.ceil(countdown-.6):'GO!';if(Math.ceil(countdown)!==old)sound(countdown>.6?650:1200,.13);if(countdown<=.6){changeState('RACING');elapsed=0;phaseTime=0;}}}
 else if(state==='RACING'){// Bounded physics substeps; race clock uses the unscaled monotonic wall interval.
 elapsed=duel?Math.max(elapsed,Date.now()+duel.clockOffset-duel.startAt):elapsed+raw*1000;let remaining=dt;while(remaining>0&&state==='RACING'){const step=Math.min(remaining,1/120);if(duel)drive(player,step);else{for(const r of racers)drive(r,step);collision();}if(mode==='item')updateItems(step);remaining-=step;}rankRacers();updateModels(dt);updateParticles(dt);if($('#countdown'))$('#countdown').textContent=phaseTime<.7?'GO!':'';}
 else if(state==='FINISHED'){updateParticles(dt);if(phaseTime>1.7)results();}else if(state==='RECORD_CARD'&&phaseTime>3.6)hall(true);
 if(fromRace&&['FINISHED','RESULT','RECORD_CARD','HALL_OF_FAME'].includes(state)&&racers.some(r=>r.id&&r.finishTime===null)){elapsed+=raw*1000;let rem=dt;while(rem>0){const step=Math.min(rem,1/120);for(const r of racers)if(r.id&&r.finishTime===null)drive(r,step);if(mode==='item')updateItems(step);rem-=step;}rankRacers();updateModels(dt);if(state==='RESULT')for(const r of racers){const row=ui.querySelector('[data-racer="'+r.id+'"]');if(row)row.lastElementChild.textContent=r.finishTime!==null?formatTime(r.finishTime):'주행 중 · '+Math.min(3,r.lap+1)+' LAP';}}if(duel&&['DUEL_WAIT','COUNTDOWN','RACING','FINISHED','DUEL_RESULT'].includes(state)&&now>=duel.nextPoll)void pollDuel();if(['RACING','COUNTDOWN','FINISHED'].includes(state))updateHUD();updateCamera(dt);if(engineGain){engineGain.gain.setTargetAtTime(state==='RACING'&&!muted?.018:0,audio.currentTime,.08);engine.frequency.setTargetAtTime(48+(player?.speed||0)*3,audio.currentTime,.08);}
 if(debug&&player)$('#debug').textContent=`FPS ${fps.toFixed(0)} | ${state}\nspeed ${player.speed.toFixed(2)}\nforwardVelocity ${player.forwardVelocity.toFixed(2)}\nlateralVelocity ${player.lateralVelocity.toFixed(2)}\nisDrifting ${player.isDrifting}\ndriftCharge ${player.driftCharge.toFixed(2)}\nboostCount ${player.boostCount}\nlap ${player.lap} / 3\ncheckpoint ${player.checkpoint} / ${CP}\nraceProgress ${player.raceProgress.toFixed(3)}\nposition ${player.rank} / 6\nsurface ${player.surface}\ncurrentLapTime ${formatTime(elapsed-player.lapStart)}\nbestLapTime ${formatTime(player.bestLap)}`;
 renderer.render(scene,camera);
}
setPreview();menu();$('#loading').remove();requestAnimationFrame(frame);
// Read-only diagnostics aid browser smoke tests without changing race eligibility.
window.KartRush={get state(){return state;},get racers(){return racers.map(r=>({id:r.id,name:r.name,character:CHARACTERS[r.charIndex].name,lap:r.lap,checkpoint:r.checkpoint,rank:r.rank,speed:r.speed,drifting:r.isDrifting,lateralVelocity:r.lateralVelocity,lapTimes:[...r.lapTimes]}));},get elapsed(){return elapsed;},formatTime,loadRecords,CONFIG};
})();


