const fs=require('node:fs');
const assert=require('node:assert/strict');
const {chromium}=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{
const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
// Instrument only the in-memory test response. Production has no autopilot, time skip or finish shortcuts.
let code=fs.readFileSync('game.js','utf8').replace('if(r.id){const look=','if(r.id||window.__autopilot){const look=');
code=code.replace('renderer.render(scene,camera);','if(!window.__fast)renderer.render(scene,camera);');
code=code.replace('setPreview();menu();$(\'#loading\').remove();requestAnimationFrame(frame);',`setPreview();menu();$('#loading').remove();window.__test={tick(n){window.__fast=true;for(let i=0;i<n;i++)frame(last+1000/60);window.__fast=false;renderer.render(scene,camera);},racers, getRacers:()=>racers, updateItems,sample,getEffects:()=>effects,getBoxes:()=>boxes,useItem,hit,resetRacer,checkpoint,startRace,saveRecord,results,recordCard,loadRecords,keys, getElapsed:()=>elapsed};`);
await page.route('**/game.js',r=>r.fulfill({contentType:'text/javascript',body:code}));await page.addInitScript(()=>{window.requestAnimationFrame=()=>0;});
await page.goto('http://127.0.0.1:4173');await page.waitForFunction(()=>window.__test);
await page.click('#start');await page.fill('#name','테스터');await page.click('#next');await page.click('[data-char="5"]');await page.click('#choose');await page.click('#race');
await page.evaluate(()=>{window.__autopilot=true;__test.tick(200);});
for(let i=0;i<12;i++){console.log('PROGRESS',i,await page.evaluate(()=>{__test.tick(1800);return {state:KartRush.state,r:KartRush.racers.map(r=>[r.id,r.lap,r.checkpoint,Math.round(r.speed)])};}));if(await page.evaluate(()=>KartRush.state==='RESULT'))break;}
assert.equal(await page.evaluate(()=>KartRush.state),'RESULT');
await page.screenshot({path:'test-result.png'});const stats=await page.evaluate(()=>KartRush.racers);assert.equal(stats[0].lapTimes.length,3);
await page.click('#record');await page.evaluate(()=>__test.tick(60));await page.waitForTimeout(1700);await page.screenshot({path:'test-record.png'});await page.evaluate(()=>__test.tick(180));assert.equal(await page.evaluate(()=>KartRush.state),'HALL_OF_FAME');await page.screenshot({path:'test-hall.png'});
let records=await page.evaluate(()=>KartRush.loadRecords());assert.equal(records.length,1);assert.equal(records[0].bestLapTime,Math.min(...stats[0].lapTimes));assert.ok(await page.locator('.mine').count());
await page.evaluate(()=>__test.saveRecord());assert.equal((await page.evaluate(()=>KartRush.loadRecords())).length,1);
await page.reload();await page.waitForFunction(()=>window.__test);assert.equal((await page.evaluate(()=>KartRush.loadRecords())).length,1);
await page.evaluate(()=>{localStorage.setItem('kartRushHallOfFame','invalid');});assert.equal((await page.evaluate(()=>KartRush.loadRecords())).length,0);
await page.evaluate(()=>{const rows=Array.from({length:14},(_,i)=>({playerName:'test',characterId:'pikachu',characterName:'피카츄',bestLapTime:50000-i*500,totalTime:150000,mode:'speed',date:new Date().toISOString()}));localStorage.setItem('kartRushHallOfFame',JSON.stringify(rows));});records=await page.evaluate(()=>KartRush.loadRecords());assert.equal(records.length,10);assert.equal(records[0].bestLapTime,43500);
await page.click('#start');await page.fill('#name','아이템테스트');await page.click('#next');await page.click('#choose');await page.click('[data-mode="item"]');await page.click('#race');await page.evaluate(()=>__test.tick(200));
console.log('COLLISIONS',await page.evaluate(()=>{const t=__test,rs=t.getRacers(),p=rs[0],target=rs[1],out=[];for(const r of rs){r.x=1000+r.id*100;r.z=1000;}p.x=0;p.z=0;p.yaw=0;target.x=0;target.z=10;p.items=[0];t.useItem(p);for(let i=0;i<60;i++)t.updateItems(1/120);if(target.stun<=0)throw Error('Missile did not hit');out.push('missile');target.stun=0;target.x=0;target.z=24;p.items=[1];t.useItem(p);for(let i=0;i<140;i++)t.updateItems(1/120);if(target.slow<=0)throw Error('Bomb did not hit');out.push('bomb');target.x=0;target.z=-3;p.items=[2];t.useItem(p);t.updateItems(.01);if(target.spin<=0)throw Error('Trap did not hit');out.push('trap');p.items=[3];t.useItem(p);t.hit(p,0);if(p.shield!==0||p.stun>0)throw Error('Shield did not block');out.push('shield');p.items=[4];t.useItem(p);if(p.boostTime!==2)throw Error('Boost did not activate');out.push('boost');t.startRace();t.tick(200);return out;}));console.log('ITEM TEST',await page.evaluate(()=>{const r=__test.getRacers()[0];const result=[];for(let type=0;type<5;type++){r.items=[type];__test.useItem(r);result.push({type,remaining:r.items.length,shield:r.shield,boost:r.boostTime});}r.shield=3;__test.hit(r,0);result.push({shieldAfterHit:r.shield,stun:r.stun});return result;}));
for(let i=0;i<12;i++){const res=await page.evaluate(()=>{window.__autopilot=true;__test.tick(1800);return {state:KartRush.state,r:KartRush.racers.map(r=>[r.id,r.lap,r.checkpoint])};});console.log('ITEM RACE',i,res);if(res.state==='RESULT')break;}
assert.equal(await page.evaluate(()=>KartRush.state),'RESULT');await page.evaluate(()=>__test.tick(7200));assert.ok((await page.evaluate(()=>KartRush.racers)).every(r=>r.lap===3));assert.deepEqual(errors,[]);console.log('PASS all integration assertions');await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
